url: http://www.angusafe.com

title: 安谷保险柜官网

keywords: 安谷保险柜,猛犸保险柜,保险柜,家用保险柜,保险柜品牌

description: 佛山市安谷保险柜制造有限公司专业保险柜制造厂家主要生产销售安谷保险柜、猛犸保险柜、保险柜、家用保险柜以及保险柜品牌等安防产品。

permalink: /products/:title.html

tel1: 13889928126

tel2: 13726339980

tel3: 0757-29283570

relative_permalinks: false

exclude:
  - README.md

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/js
    - _assets/css
  compress:
    css: true
    js: true
  gzip: []
