url: http://www.slhtml.com

title: 安谷保险柜官网

keywords: 封箱机,打包机,收缩机,缠绕机

description: 佛山市顺德区天键包装材料机械有限公司专业生产封箱机、打包机、收缩机、缠绕机等包装机械，为客户设计订造适合自己的后工序自动化包装方案。

permalink: /products/:title.html

relative_permalinks: false

exclude:
  - README.md

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/js
    - _assets/css
  js_compressor: uglifier
  css_compressor: sass
  cache: true
  cache_assets: true
  gzip: []
