url: http://www.angusafe.com

title: 安谷保险柜官网

keywords: 保险柜

description: 安谷保险柜专业制造保险柜、保险箱、家用保险柜、家用保险箱等安防产品。

permalink: /products/:title.html

relative_permalinks: false

exclude:
  - README.md

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/js
    - _assets/css
  js_compressor: uglifier
  css_compressor: sass
  cache: true
  cache_assets: true
  gzip: []
